databases:
  - name: db1
    url: mysql+pymysql://user:password@localhost:3307/app
    weight: 1

  - name: db2
    url: mysql+pymysql://user:password@localhost:3308/app
    weight: 1

  - name: db3
    url: mysql+pymysql://user:password@localhost:3309/app
    weight: 1
  
  - name: db4
    url: mysql+pymysql://user:password@localhost:3310/app
    weight: 1

  - name: db5
    url: mysql+pymysql://user:password@localhost:3311/app
    weight: 1
